version: "3.7"

services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "443:443"
      - "8888:8888"
      - "3000:3000"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/certs/:/etc/ssl/certs/
    networks:
      shopper_devnet:

networks:
  shopper_devnet:
    external: true